# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bef1a81bb3eb766678d9d082842b13b121672c7b044456b76370d66ce606149c1c41075ec0905174b0f270cd404fa1fd8d55ccfb6134e0f8f6c7f2ee664ebd0

test:
  secret_key_base: 161960769e4540c3e03afa6cd414c1b7f2a22d9deacc02aeae61b75c39e6d99fdf5553c2a57f295ef35a440ae940f30f1cdd14855da813e96a5af122c74ad76b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
